# This is a basic workflow to help you get started with Actions

name: TestSuite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  #  schedule:
  #    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
    env:
        USERNAME: "vim"
        USER_UID: 1000
        USER_GID: 1000
    container:
        image: ocaml/opam:ubuntu-22.04
        options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Fix Namespaces
        #run: chmod u+s /usr/bin/bwrap
        run: if ["$USER_GID" != "1000"] || ["USER_UID" != "1000"]; then groupmod --gid $USER_GID $USERNAME && usermod -uid $USER_UID -gid $USER_GID $USERNAME && chown -R $USER_UID:$USER_GID /home/$USERNAME

      - name: OCaml setup
        run: su - $USERNAME && opam init && opam update && opam install base core_kernel ounit qcheck dune ocamlformat
