# This is a basic workflow to help you get started with Actions

name: DoccanoInit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#  schedule:
#    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container:
      image: ocaml:opam
    steps:
      - uses: actions/checkout@v3

      - name: OCaml setup
        run: opam update && opam install base core_kernel ounit qcheck dune ocamlformat
